using System;
using System.Collections.Generic;
using System.Text;

namespace Getools.Lib
{
    public static class Utility
    {
        public static string GetAutoGeneratedAssemblyVersion()
        {
            var assembly = System.Reflection.Assembly.GetAssembly(typeof(FindMe));
            string version = assembly.GetName().Version.ToString();
            string assemblyName = assembly.GetName().Name;

            return $"{assemblyName}: {version}";
        }
    }
}
