using System;
using System.Collections.Generic;
using System.Text;

namespace Getools.Lib
{
    /// <summary>
    /// General utility methods.
    /// </summary>
    public static class Utility
    {
        /// <summary>
        /// Gets standard string giving the assembly name and version.
        /// </summary>
        /// <returns>String.</returns>
        public static string GetAutoGeneratedAssemblyVersion()
        {
            var assembly = System.Reflection.Assembly.GetAssembly(typeof(FindMe));
            string version = assembly.GetName().Version.ToString();
            string assemblyName = assembly.GetName().Name;

            return $"{assemblyName}: {version}";
        }
    }
}
