using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Getools.Lib.Error;
using Getools.Lib.Game.Asset.Intro;
using Getools.Lib.Game.Asset.SetupObject;

namespace Getools.Lib.Game.Asset.Setup
{
    public class StageSetupFile
    {
        /// <summary>
        /// C headers to #include when building .c files.
        /// </summary>
        public static List<string> IncludeHeaders = new List<string>()
        {
            "ultra64.h",
            "stagesetup.h",
        };

        public int PathTableDataOffset { get; set; }

        public List<PathTable> PathTableData { get; set; } = new List<PathTable>();

        public int PathTablesOffset { get; set; }

        public List<SetupPathTableEntry> PathTables { get; set; } = new List<SetupPathTableEntry>();

        public int PathLinkDataOffset { get; set; }

        public List<PathListing> PathLinkData { get; set; } = new List<PathListing>();

        public int PathLinksOffset { get; set; }

        public List<SetupPathLinkEntry> PathLinkEntries { get; set; } = new List<SetupPathLinkEntry>();

        public int IntrosOffset { get; set; }

        public List<IIntro> Intros { get; set; } = new List<IIntro>();

        public int ObjectsOffset { get; set; }

        public List<ISetupObject> Objects { get; set; } = new List<ISetupObject>();

        public int PathSetsDataOffset { get; set; }

        public List<PathSet> PathSetsData { get; set; } = new List<PathSet>();

        public int PathSetsOffset { get; set; }

        public List<SetupPathSetEntry> PathSets { get; set; } = new List<SetupPathSetEntry>();

        public int AiDataOffset { get; set; }

        public byte[] AiData { get; set; }

        public int AiListOffset { get; set; }

        public List<SetupAiListEntry> AiLists { get; set; } = new List<SetupAiListEntry>();

        public int PadListOffset { get; set; }

        public List<Pad> PadList { get; set; } = new List<Pad>();

        public int Pad3dListOffset { get; set; }

        public List<Pad3d> Pad3dList { get; set; } = new List<Pad3d>();

        public int PadNamesOffset { get; set; }

        public List<StringPointer> PadNames { get; set; } = new List<StringPointer>();

        public int Pad3dNamesOffset { get; set; }

        public List<StringPointer> Pad3dNames { get; set; } = new List<StringPointer>();

        public byte[] RodataPrequelFiller { get; set; }

        public void DeserializeFix()
        {
            foreach (var entry in PathLinkEntries)
            {
                entry.Indeces.first
            }
        }

        /// <summary>
        /// Builds the entire .c file describing setup and writes to stream at the current position.
        /// </summary>
        /// <param name="sw">Stream to write to</param>
        internal void WriteToCFile(StreamWriter sw)
        {
            int index = 0;
            sw.WriteLine("/*");

            foreach (var prefix in Config.COutputPrefix)
            {
                sw.WriteLine($"* {prefix}");
            }

            sw.WriteLine($"* {DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}");

            var assemblyInfo = Utility.GetAutoGeneratedAssemblyVersion();

            sw.WriteLine($"* {assemblyInfo}");
            sw.WriteLine("*/");
            sw.WriteLine();

            foreach (var filename in IncludeHeaders)
            {
                sw.WriteLine($"#include \"{filename}\"");
            }

            sw.WriteLine();

            /*
             * standard section order:
             *
             * - pad list
             * - pad3d list
             * - object list
             * - intro definitions
             * - path links
             * - pad3d names
             * - path tables
             * - pad names
             * - path sets
             * - ai lists
             */

            /******************************************************************************************
             * Begin pad list
             */

            sw.WriteLine($"{Pad.CTypeName} padlist[] = {{");

            for (int i = 0; i < PadList.Count - 1; i++)
            {
                sw.WriteLine(PadList[i].ToCInlineDeclaration(Config.DefaultIndent) + ",");
            }

            if (PadList.Any())
            {
                sw.WriteLine(PadList.Last().ToCInlineDeclaration(Config.DefaultIndent));
            }

            sw.WriteLine("};");

            /*
             * End pad list
             */

            sw.WriteLine();
            sw.WriteLine();

            /******************************************************************************************
             * Begin pad3d list
             */

            sw.WriteLine($"{Pad3d.CTypeName} pad3dlist[] = {{");

            for (int i = 0; i < Pad3dList.Count - 1; i++)
            {
                sw.WriteLine(Pad3dList[i].ToCInlineDeclaration(Config.DefaultIndent) + ",");
            }

            if (Pad3dList.Any())
            {
                sw.WriteLine(Pad3dList.Last().ToCInlineDeclaration(Config.DefaultIndent));
            }

            sw.WriteLine("};");

            /*
             * End pad3d list
             */

            sw.WriteLine();
            sw.WriteLine();

            /******************************************************************************************
             * Begin object list
             */

            sw.WriteLine($"s32 objlist[] = {{");

            index = 0;
            for (int i = 0; i < Objects.Count - 1; i++, index++)
            {
                sw.WriteLine($"{Config.DefaultIndent}/* {nameof(ISetupObject.Type)} = {Objects[i].Type}; index = {index} */");
                sw.WriteLine(Objects[i].ToCInlineS32Array(Config.DefaultIndent) + ",");
            }

            if (Objects.Any())
            {
                sw.WriteLine($"{Config.DefaultIndent}/* {nameof(ISetupObject.Type)} = {Objects.Last().Type}; index = {index} */");
                sw.WriteLine(Objects.Last().ToCInlineS32Array(Config.DefaultIndent));
            }

            sw.WriteLine("};");

            /*
             * End object list
             */

            /******************************************************************************************
             * Begin intro definitions
             */

            sw.WriteLine($"s32 intro[] = {{");

            index = 0;
            for (int i = 0; i < Intros.Count - 1; i++, index++)
            {
                sw.WriteLine($"{Config.DefaultIndent}/* {nameof(IIntro.Type)} = {Intros[i].Type}; index = {index} */");
                sw.WriteLine(Intros[i].ToCInlineS32Array(Config.DefaultIndent) + ",");
            }

            if (Intros.Any())
            {
                sw.WriteLine($"{Config.DefaultIndent}/* {nameof(IIntro.Type)} = {Intros.Last().Type}; index = {index} */");
                sw.WriteLine(Intros.Last().ToCInlineS32Array(Config.DefaultIndent));
            }

            sw.WriteLine("};");

            /*
             * End intro definitions
             */

            /******************************************************************************************
             * Begin path links
             */

            ////// code

            /*
             * End path links
             */

            /******************************************************************************************
             * Begin pad3d names
             */

            ////// code

            /*
             * End pad3d names
             */

            /******************************************************************************************
             * Begin path tables
             */

            ////// code

            /*
             * End path tables
             */

            /******************************************************************************************
             * Begin pad names
             */

            ////// code

            /*
             * End pad names
             */

            /******************************************************************************************
             * Begin path sets
             */

            ////// code

            /*
             * End path sets
             */

            /******************************************************************************************
             * Begin ai lists
             */

            ////// code

            /*
             * End ai lists
             */
        }
    }
}
